theme: jekyll-theme-slate
title: radsecproxy
description: a generic RADIUS proxy with RadSec support
show_downloads: true
download_version: v1.10.0
github:
  repository_url: https://github.com/radsecproxy/radsecproxy
  tar_url: https://github.com/radsecproxy/radsecproxy/releases/download/1.10.0/radsecproxy-1.10.0.tar.gz
  asc_url: https://github.com/radsecproxy/radsecproxy/releases/download/1.10.0/radsecproxy-1.10.0.tar.gz.asc
